language: go
go: tip
install:
- go get github.com/boltdb/bolt
- go get github.com/juju/errors
- go get github.com/julienschmidt/httprouter
- go get github.com/segmentio/go-log
- go get gopkg.in/check.v1
script:
- go test -v ./...
notifications:
  slack:
    secure: HUdnVoynzjMKvsSH4hkJ494BpHlDQ9ReifLlCsu+5rpxt85PTSbKn7/IpGT692mox2x9gG/JgiMu5Ob0FyVVubO1I9D6onxHbH4GkPjJ8FfV90tNnk2tFmQbCaZGBmYX4LuC9iBxz53eQF4kbbnrhJ84nqM88i+RvMuIYgo6r7c=
